### ISSUE TITLE
Add XSD ComplexType name "SpatialDefinitionFormatType" to Common.xsd as enumerations to align to updated 950002, Clause 5.2

### ISSUE THREAD

**Issue by factoryiq** [ETPartners/b2mmlv7beta#58]
**Background**
In Common Schema, Issue #57 changed complexType name="SpatialDefinitionType" by changing "Format" element from IdentifierType to "SpatialDefinitionFormatType".  This issue Adds  SpatialDefinitionFormatType as a list of enumerations comply and align to updated ISA-950002, Clause 5.2 Spatial definitions, Table 19 - Attributes of spatial definition and Example 4 values.  

**Supporting Documents**
_ISA-950002 JWG5 CDV01 version (2019 12)_
Clause 5.2 Spatial definitions, 
    Table 19 - Attributes of spatial definition 
    Example 4.  List of Possible Defined Values. 

**Impacted Types and Solution**
_B2MML-Common.xsd,_ 
      "SpatialDefinitionType"

1. To align with B2MML Design method for doing enumerations, Updated common.xsd by 
moving SpatialFormatDataType to a new location based on alphabetic order of type name.
2. CHANGED: <xsd:complexType name="SpatialFormatDataType">
           TO: <xsd:complexType name="SpatialDefintionFormat1Type">
3. ADD: complexType name="SpatialDefinitionFormatType"
4. ADD:  See below for complete xsd.
complexType name="SpatialDefinitionFormatType"
complexType name="SpatialDefinitionFormat1Type"

950002 Example 4 defines the 8 common format types that are used across 95% of market as spatial data identification standards. 
These include WKT, WKB, GML, KML, GPX, GeoJSON, SVG, and other. The documentation of these types are listed below in the XSD schema complex type.

The Spatial Format Enumeration Data Types are as follows:
1. WKT - Well Known Text ! markup language defined in the ISO/IEC 13249-3:2011 Standard
2. WKB - Well Known Binary ! representation of WKT defined in the ISO/IEC 13249-3:2011 Standard
3. GML - Geography markup language - OpenGIS Geography Markup Language Encoding Standard
4. KML - Keyhole markup language - KML 2.2 defined by the Open Geospatial Consortium (OGC)
5. GPX - GPS exchange format data used from mobile devices.
6. GeoJSON - Geographical format for spatial data in JSON format.
7. SVG - Scalable Vector Graphics in XML with 2D and 3D lines, poly lines, or solid objects.

```xml
   <xsd:complexType name="SpatialDefinitionFormat1Type">
	<xsd:simpleContent>
	    <xsd:restriction base="CodeType">
		<xsd:enumeration value="WKT"/> <!--Well-Known Text ISO/IEC 13249-3:2011 Standard -->  
	        <xsd:enumeration value="WKB"/> <!--Well-Known Binary ISO/IEC 13249-3:2011 Standard --> 
                <xsd:enumeration value="GML"/> <!--Geographical Markup Language  --> 
                <xsd:enumeration value="KML"/> <!--Keyhole Markup Language  --> 
                <xsd:enumeration value="GPX"/> <!--GPS Exchange Format  --> 
                <xsd:enumeration value="GeoJSON"/> <!--Geographical JSON 1.0 Format  --> 
                <xsd:enumeration value="SVG"/> <!--Scalable Vector Graphics XML 2D or 3D format -->
		<xsd:enumeration value="Other"/> <!--Other undefined Spatial Unknown format --> 
            </xsd:restriction>
        </xsd:simpleContent>
    </xsd:complexType>	
    <!--     --> 

    <xsd:complexType name="SpatialDefinitionFormatType">
		<xsd:annotation> 
			<xsd:documentation>
For the SpatialDefintionType, the Spatial Definition Format element's Enumeration types as defined in ISAS-950002 commom object models as Spatial data definitions.    -->
			</xsd:documentation>
		</xsd:annotation> 
                <xsd:simpleContent>
                        <xsd:extension base="SpatialDefnitionFormat1Type">
                        <xsd:attribute name="OtherValue" type="xsd:string"/>
                        </xsd:extension>
                </xsd:simpleContent>
    </xsd:complexType>	
```

**Comment by Dennis-Brandl** [comment]
I agree with gerardmoloneyetpartners, these are only examples and should not be enumerated.

**Comment by gerardmoloneyetpartners** [comment]
Hi @Dennis-Brandl, my comment on 3 Feb was not to agree with you, it was to pass the MESA github comments back here to etp github (prior to us giving you access).

However, in MESA github https://github.com/MESAInternational/B2MML-BatchML/issues/50 you have commented _Those are still just examples, but its ok to leave this change in place, and let people use the "OtherValue" where needed.
Issue closed._  Does this mean the changes were accepted AND implemented? I'll try and check the code now to verify.

**Comment by gerardmoloneyetpartners** [comment]
OK, I can see the fix was implemented as proposed.
Moving this to the 'committed by MESA' milestone and closing it.
